-d D:\BaiduSyncdisk\TongjiRubbishBin\ISP\FPGA_ISP\test1\impl\gwsynthesis\test1.vg
-p GW5AST-138B-PBGA676A-1
-pn GW5AST-LV138PG676AES
-cst D:\BaiduSyncdisk\TongjiRubbishBin\ISP\FPGA_ISP\test1\src\test1.cst
-cfg D:\BaiduSyncdisk\TongjiRubbishBin\ISP\FPGA_ISP\test1\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-correct_hold 1
-route_maxfan 23
